exclude: '.git'
default_stages: [ commit ]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        files: (^|/)a/.+\.(py|html|sh|css|js)$

  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        name: flake8
        language: python
        types:
          - python
  - repo: https://github.com/pycqa/isort
    rev: "5.9.3"
    hooks:
      - id: isort
        name: isort (python)
        language: python
        types:
          - python
        args:
          - --check
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
    hooks:
      - id: mypy
        entry: bash -c 'mypy "$@" || true' --
